### ISSUE TITLE
missing dev support for new m1 chips

### ISSUE THREAD

**Issue by shyam-patel-kira** [witnet/website#191]
To reproduce run ``` yarn install ``` on any m1 machine.

**Comment by aesedepece** [comment]
Hi @shyam-patel-kira! Is this referred to the witnet website itself?

**Comment by shyam-patel-kira** [comment]
We resolved it by using "sass" version 1.36.0 instead of "node-sass". If ya want you can just add this little point in README.md maybe.

**Comment by aesedepece** [comment]
Thanks for the info @shyam-patel-kira! Isn't it better to rather replace `node-sass` for `sass` in the project dependencies altogether?

**Comment by shyam-patel-kira** [comment]
Yes...replacing can also solve the problem.

**Comment by Tommytrg** [comment]
We have redesigned the website and this is no longer an issue
