### ISSUE TITLE
[Discussion] Redesign strategy for Witnet 2.0

### ISSUE THREAD

**Issue by gabaldon** [witnet/website#356]
Discussion points:

- Color palette
- Illustrations
- New website content

**Comment by Tommytrg** [comment]
Style guide draft: https://www.figma.com/file/RWXQEchA5FWzsL8L3pyLbG/Witnet-2.0-Styleguide?type=design&node-id=0%3A1&mode=design&t=NkEcdnbcXfxmEsyq-1
