### ISSUE TITLE
Decide minimum viable content

### ISSUE THREAD

**Issue by mariocao** [witnet/website#37]

**Comment by aesedepece** [comment]
Done. The landing page will include the following components:
- Hero with mini-pitch
- Characterization of witnet as an oracle
- Introduction to the wit token
- Ecosystem overview (pointers to node, sheikah, explorer...)
- Community overview (how to get involved & bounties)
- Footer

**Comment by aesedepece** [comment]
We'll be happy to receive personal shortlists on "what shouldn't be left out" for the bare bones landing page.
