### ISSUE TITLE
Wrong Socials placement 

### ISSUE THREAD

**Issue by Tommytrg** [witnet/website#413]
When the website is loaded, sometimes the text is aligned to the left and others to the right. Apparently, this is happening because when the socials are misplaced, text's width is `0` instead of `40px`.

![image](https://github.com/user-attachments/assets/2381baab-8b8e-4f00-8de3-50f17f5083ef)
![image](https://github.com/user-attachments/assets/7b344042-f222-4644-9d0f-531c7ff38c38)

**Comment by gabaldon** [comment]
closed by https://github.com/witnet/wit-vue-ui/pull/39
