### ISSUE TITLE
Fonts are off

### ISSUE THREAD

**Issue by aesedepece** [witnet/website#92]
The font families currently being used are not the same than in the design. We need to pay attention to the usage of the two different fonts (`Avenir Next Pro` for titles and `Almarai` for paragraphs) and also negative letter spacing.

**Comment by aesedepece** [comment]
We may need to self-host the fonts, as those are not available on Google Fonts.

**Comment by aesedepece** [comment]
We already got the license for Avenir Next Pro. Let's make sure to update it when possible.

**Comment by gabaldon** [comment]
This was already fixed in commit: [5e121bb1b076247087dd3dc2ee5cdac30d43147f](5e121bb1b076247087dd3dc2ee5cdac30d43147f)
