### ISSUE TITLE
Website is horizontally scrollable using triple-tap or middle click gestures

### ISSUE THREAD

**Issue by aesedepece** [witnet/website#94]
Website is horizontally scrollable using triple-tap or middle click gestures.

This normally happens because the size of the document or a top level element is set to 100vw instead of 100%, so even if the viewport looks right at first, elements are actually overflowing behind the scrollbar.

**Comment by gabaldon** [comment]
This was fixed in commit: [275092bfd7aa583c69bb69065fe8528c249c1442](https://github.com/witnet/website/commit/275092bfd7aa583c69bb69065fe8528c249c1442)
